---
- name: NXOS High Utilization
  hosts: all
  ignore_errors: true
  gather_facts: false
  tasks:      
  - name: interface high utilizaiton
    include_role:
      name: net_nxos
      tasks_from: interface_high_utilization.yml
  