---
- name: Check interface high utilization
  hosts: all
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Check connectivity
    ping: 
    register: ping_result
  - name: Display ping result
    debug:
      msg: "{{ping_result}}"
  - name: include role
    include_role:
      name: ios_utilization
    when: ping_result.ping == 'pong'