---
- name: Check interface high utilization
  hosts: all
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Check connectivity
    ping: 
    register: ping_result
  - name: Display ping result
    debug:
      msg: "{{ping_result}}"
  
  - name: Get utilization
      custom_module:
        string: "reliability 255/255, txload 154/255, rxload 101/255"
      register: result

  - name: Display utilization
    debug:
      var: result

  - name: include role
    include_role:
      name: ios_utilization
    when: ping_result.ping == 'pong'