- name: Check network utilization of interface on network device
  nxos_command:
    commands:
      - show interface {{interface_name}} | i txload|rxload
  register: interface_load

- name: Display interface load
  debug:
    msg: "{{interface_load.stdout_lines}}"

- name: Get utilization
  extract_utilization:
    string: "{{interface_load.stdout_lines|string}}"
  register: result

- name: Display utilization
  debug:
    var: result